version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_CLERK_FRONTEND_API: ${NEXT_PUBLIC_CLERK_FRONTEND_API}
    container_name: finova_web_prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm start"
    restart: unless-stopped
